package wimod

const (
	DEVMGMT_ID byte = 0x01
	LORAWAN_ID byte = 0x10
)

const (
	DEVMGMT_MSG_PING_REQ              uint16 = 0x0101
	DEVMGMT_MSG_PING_RSP              uint16 = 0x0102
	DEVMGMT_MSG_GET_DEVICE_INFO_REQ   uint16 = 0x0103
	DEVMGMT_MSG_GET_DEVICE_INFO_RSP   uint16 = 0x0104
	DEVMGMT_MSG_GET_FW_INFO_REQ       uint16 = 0x0105
	DEVMGMT_MSG_GET_FW_INFO_RSP       uint16 = 0x0106
	DEVMGMT_MSG_RESET_REQ             uint16 = 0x0107
	DEVMGMT_MSG_RESET_RSP             uint16 = 0x0108
	DEVMGMT_MSG_SET_OPMODE_REQ        uint16 = 0x0109
	DEVMGMT_MSG_SET_OPMODE_RSP        uint16 = 0x010A
	DEVMGMT_MSG_GET_OPMODE_REQ        uint16 = 0x010B
	DEVMGMT_MSG_GET_OPMODE_RSP        uint16 = 0x010C
	DEVMGMT_MSG_SET_RTC_REQ           uint16 = 0x010D
	DEVMGMT_MSG_SET_RTC_RSP           uint16 = 0x010E
	DEVMGMT_MSG_GET_RTC_REQ           uint16 = 0x010F
	DEVMGMT_MSG_GET_RTC_RSP           uint16 = 0x0110
	DEVMGMT_MSG_GET_DEVICE_STATUS_REQ uint16 = 0x0117
	DEVMGMT_MSG_GET_DEVICE_STATUS_RSP uint16 = 0x0118
	DEVMGMT_MSG_SET_RTC_ALARM_REQ     uint16 = 0x0131
	DEVMGMT_MSG_SET_RTC_ALARM_RSP     uint16 = 0x0132
	DEVMGMT_MSG_CLEAR_RTC_ALARM_REQ   uint16 = 0x0133
	DEVMGMT_MSG_CLEAR_RTC_ALARM_RSP   uint16 = 0x0134
	DEVMGMT_MSG_GET_RTC_ALARM_REQ     uint16 = 0x0135
	DEVMGMT_MSG_GET_RTC_ALARM_RSP     uint16 = 0x0136
	DEVMGMT_MSG_RTC_ALARM_IND         uint16 = 0x0138
)

const (
	DEVMGMT_STATUS_OK                byte = 0x00
	DEVMGMT_STATUS_ERROR             byte = 0x01
	DEVMGMT_STATUS_CMD_NOT_SUPPORTED byte = 0x02
	DEVMGMT_STATUS_WRONG_PARAMETER   byte = 0x03
)

const (
	DEVMGMT_MSG_RTC_ALARM_IND_STATUS_OK    byte = 0x00
	DEVMGMT_MSG_RTC_ALARM_IND_STATUS_ERROR byte = 0x01
)

const (
	DEVMGMT_OPMODE_STANDARD byte = 0x00
	DEVMGMT_OPMODE_CUSTOMER byte = 0x03
)

const (
	LORAWAN_MSG_ACTIVATE_DEVICE_REQ       uint16 = 0x1001
	LORAWAN_MSG_ACTIVATE_DEVICE_RSP       uint16 = 0x1002
	LORAWAN_MSG_SET_JOIN_PARAM_REQ        uint16 = 0x1005
	LORAWAN_MSG_SET_JOIN_PARAM_RSP        uint16 = 0x1006
	LORAWAN_MSG_JOIN_NETWORK_REQ          uint16 = 0x1009
	LORAWAN_MSG_JOIN_NETWORK_RSP          uint16 = 0x100A
	LORAWAN_MSG_JOIN_NETWORK_TX_IND       uint16 = 0x100B
	LORAWAN_MSG_JOIN_NETWORK_IND          uint16 = 0x100C
	LORAWAN_MSG_SEND_UDATA_REQ            uint16 = 0x100D
	LORAWAN_MSG_SEND_UDATA_RSP            uint16 = 0x100E
	LORAWAN_MSG_SEND_UDATA_TX_IND         uint16 = 0x100F
	LORAWAN_MSG_RECV_UDATA_IND            uint16 = 0x1010
	LORAWAN_MSG_SEND_CDATA_REQ            uint16 = 0x1011
	LORAWAN_MSG_SEND_CDATA_RSP            uint16 = 0x1012
	LORAWAN_MSG_SEND_CDATA_TX_IND         uint16 = 0x1013
	LORAWAN_MSG_RECV_CDATA_IND            uint16 = 0x1014
	LORAWAN_MSG_RECV_ACK_IND              uint16 = 0x1015
	LORAWAN_MSG_RECV_NO_DATA_IND          uint16 = 0x1016
	LORAWAN_MSG_SET_RSTACK_CONFIG_REQ     uint16 = 0x1019
	LORAWAN_MSG_SET_RSTACK_CONFIG_RSP     uint16 = 0x101A
	LORAWAN_MSG_GET_RSTACK_CONFIG_REQ     uint16 = 0x101B
	LORAWAN_MSG_GET_RSTACK_CONFIG_RSP     uint16 = 0x101C
	LORAWAN_MSG_REACTIVATE_DEVICE_REQ     uint16 = 0x101D
	LORAWAN_MSG_REACTIVATE_DEVICE_RSP     uint16 = 0x101E
	LORAWAN_MSG_DEACTIVATE_DEVICE_REQ     uint16 = 0x1021
	LORAWAN_MSG_DEACTIVATE_DEVICE_RSP     uint16 = 0x1022
	LORAWAN_MSG_FACTORY_RESET_REQ         uint16 = 0x1023
	LORAWAN_MSG_FACTORY_RESET_RSP         uint16 = 0x1024
	LORAWAN_MSG_SET_DEVICE_EUI_REQ        uint16 = 0x1025
	LORAWAN_MSG_SET_DEVICE_EUI_RSP        uint16 = 0x1026
	LORAWAN_MSG_GET_DEVICE_EUI_REQ        uint16 = 0x1027
	LORAWAN_MSG_GET_DEVICE_EUI_RSP        uint16 = 0x1028
	LORAWAN_MSG_GET_NWK_STATUS_REQ        uint16 = 0x1029
	LORAWAN_MSG_GET_NWK_STATUS_RSP        uint16 = 0x102A
	LORAWAN_MSG_SEND_MAC_CMD_REQ          uint16 = 0x102B
	LORAWAN_MSG_SEND_MAC_CMD_RSP          uint16 = 0x102C
	LORAWAN_MSG_RECV_MAC_CMD_IND          uint16 = 0x102D
	LORAWAN_MSG_SET_CUSTOM_CFG_REQ        uint16 = 0x1031
	LORAWAN_MSG_SET_CUSTOM_CFG_RSP        uint16 = 0x1032
	LORAWAN_MSG_GET_CUSTOM_CFG_REQ        uint16 = 0x1033
	LORAWAN_MSG_GET_CUSTOM_CFG_RSP        uint16 = 0x1034
	LORAWAN_MSG_GET_SUPPORTED_BANDS_REQ   uint16 = 0x1035
	LORAWAN_MSG_GET_SUPPORTED_BANDS_RSP   uint16 = 0x1036
	LORAWAN_MSG_SET_LINKADRREQ_CONFIG_REQ uint16 = 0x103B
	LORAWAN_MSG_SET_LINKADRREQ_CONFIG_RSP uint16 = 0x103C
	LORAWAN_MSG_GET_LINKADRREQ_CONFIG_REQ uint16 = 0x103D
	LORAWAN_MSG_GET_LINKADRREQ_CONFIG_RSP uint16 = 0x103E
)

const (
	LORAWAN_STATUS_OK                    byte = 0x00
	LORAWAN_STATUS_ERROR                 byte = 0x01
	LORAWAN_STATUS_CMD_NOT_SUPPORTED     byte = 0x02
	LORAWAN_STATUS_WRONG_PARAMETER       byte = 0x03
	LORAWAN_STATUS_WRONG_DEVICE_MODE     byte = 0x04
	LORAWAN_STATUS_DEVICE_NOT_ACTIVATED  byte = 0x05
	LORAWAN_STATUS_DEVICE_BUSY           byte = 0x06
	LORAWAN_STATUS_QUEUE_FULL            byte = 0x07
	LORAWAN_STATUS_LENGTH_ERROR          byte = 0x08
	LORAWAN_STATUS_NO_FACTORY_SETTINGS   byte = 0x09
	LORAWAN_STATUS_CHANNEL_BLOCKED       byte = 0x0A
	LORAWAN_STATUS_CHANNEL_NOT_AVAILABLE byte = 0x0B
)

const (
	LORAWAN_NETWORK_STATUS_INACTIVE     = 0x00
	LORAWAN_NETWORK_STATUS_ACTIVE_ABP   = 0x01
	LORAWAN_NETWORK_STATUS_ACTIVE_OTAA  = 0x02
	LORAWAN_NETWORK_STATUS_JOINING_OTAA = 0x03
)

const (
	LORAWAN_MSG_JOIN_NETWORK_TX_IND_STATUS_OK            = 0x00
	LORAWAN_MSG_JOIN_NETWORK_TX_IND_STATUS_OK_ATTACHMENT = 0x01
	LORAWAN_MSG_JOIN_NETWORK_TX_IND_STATUS_ERROR         = 0x02

	LORAWAN_MSG_JOIN_NETWORK_IND_STATUS_OK            = 0x00
	LORAWAN_MSG_JOIN_NETWORK_IND_STATUS_OK_ATTACHMENT = 0x01
	LORAWAN_MSG_JOIN_NETWORK_IND_STATUS_ERROR         = 0x02

	LORAWAN_MSG_SEND_UDATA_TX_IND_STATUS_OK            = 0x00
	LORAWAN_MSG_SEND_UDATA_TX_IND_STATUS_OK_ATTACHMENT = 0x01
	LORAWAN_MSG_SEND_UDATA_TX_IND_STATUS_ERROR         = 0x02
)

var alarmConstructors = map[uint16]func() WiModMessageInd{
	DEVMGMT_MSG_RTC_ALARM_IND:       func() WiModMessageInd { return NewRTCAlarmInd() },
	LORAWAN_MSG_JOIN_NETWORK_TX_IND: func() WiModMessageInd { return NewJoinNetworkTxInd() },
	LORAWAN_MSG_JOIN_NETWORK_IND:    func() WiModMessageInd { return NewJoinNetworkInd() },
	LORAWAN_MSG_SEND_UDATA_TX_IND:   func() WiModMessageInd { return NewSendUDataTxInd() },
}

func IsAlarm(code uint16) bool {
	_, ok := alarmConstructors[code]
	return ok
}
