package wimod

const (
	DEVMGMT_ID = 0x01
	LORAWAN_ID = 0x10
)

const (
	DEVMGMT_MSG_PING_REQ              = 0x01
	DEVMGMT_MSG_PING_RSP              = 0x02
	DEVMGMT_MSG_GET_DEVICE_INFO_REQ   = 0x03
	DEVMGMT_MSG_GET_DEVICE_INFO_RSP   = 0x04
	DEVMGMT_MSG_GET_FW_INFO_REQ       = 0x05
	DEVMGMT_MSG_GET_FW_INFO_RSP       = 0x06
	DEVMGMT_MSG_RESET_REQ             = 0x07
	DEVMGMT_MSG_RESET_RSP             = 0x08
	DEVMGMT_MSG_SET_OPMODE_REQ        = 0x09
	DEVMGMT_MSG_SET_OPMODE_RSP        = 0x0A
	DEVMGMT_MSG_GET_OPMODE_REQ        = 0x0B
	DEVMGMT_MSG_GET_OPMODE_RSP        = 0x0C
	DEVMGMT_MSG_SET_RTC_REQ           = 0x0D
	DEVMGMT_MSG_SET_RTC_RSP           = 0x0E
	DEVMGMT_MSG_GET_RTC_REQ           = 0x0F
	DEVMGMT_MSG_GET_RTC_RSP           = 0x10
	DEVMGMT_MSG_GET_DEVICE_STATUS_REQ = 0x17
	DEVMGMT_MSG_GET_DEVICE_STATUS_RSP = 0x18
	DEVMGMT_MSG_SET_RTC_ALARM_REQ     = 0x31
	DEVMGMT_MSG_SET_RTC_ALARM_RSP     = 0x32
	DEVMGMT_MSG_CLEAR_RTC_ALARM_REQ   = 0x33
	DEVMGMT_MSG_CLEAR_RTC_ALARM_RSP   = 0x34
	DEVMGMT_MSG_GET_RTC_ALARM_REQ     = 0x35
	DEVMGMT_MSG_GET_RTC_ALARM_RSP     = 0x36
	DEVMGMT_MSG_RTC_ALARM_IND         = 0x38
)

const (
	DEVMGMT_STATUS_OK                = 0x00
	DEVMGMT_STATUS_ERROR             = 0x01
	DEVMGMT_STATUS_CMD_NOT_SUPPORTED = 0x02
	DEVMGMT_STATUS_WRONG_PARAMETER   = 0x03
)

const (
	LORAWAN_MSG_ACTIVATE_DEVICE_REQ       = 0x01
	LORAWAN_MSG_ACTIVATE_DEVICE_RSP       = 0x02
	LORAWAN_MSG_SET_JOIN_PARAM_REQ        = 0x05
	LORAWAN_MSG_SET_JOIN_PARAM_RSP        = 0x06
	LORAWAN_MSG_JOIN_NETWORK_REQ          = 0x09
	LORAWAN_MSG_JOIN_NETWORK_RSP          = 0x0A
	LORAWAN_MSG_JOIN_NETWORK_TX_IND       = 0x0B
	LORAWAN_MSG_JOIN_NETWORK_IND          = 0x0C
	LORAWAN_MSG_SEND_UDATA_REQ            = 0x0D
	LORAWAN_MSG_SEND_UDATA_RSP            = 0x0E
	LORAWAN_MSG_SEND_UDATA_TX_IND         = 0x0F
	LORAWAN_MSG_RECV_UDATA_IND            = 0x10
	LORAWAN_MSG_SEND_CDATA_REQ            = 0x11
	LORAWAN_MSG_SEND_CDATA_RSP            = 0x12
	LORAWAN_MSG_SEND_CDATA_TX_IND         = 0x13
	LORAWAN_MSG_RECV_CDATA_IND            = 0x14
	LORAWAN_MSG_RECV_ACK_IND              = 0x15
	LORAWAN_MSG_RECV_NO_DATA_IND          = 0x16
	LORAWAN_MSG_SET_RSTACK_CONFIG_REQ     = 0x19
	LORAWAN_MSG_SET_RSTACK_CONFIG_RSP     = 0x1A
	LORAWAN_MSG_GET_RSTACK_CONFIG_REQ     = 0x1B
	LORAWAN_MSG_GET_RSTACK_CONFIG_RSP     = 0x1C
	LORAWAN_MSG_REACTIVATE_DEVICE_REQ     = 0x1D
	LORAWAN_MSG_REACTIVATE_DEVICE_RSP     = 0x1E
	LORAWAN_MSG_DEACTIVATE_DEVICE_REQ     = 0x21
	LORAWAN_MSG_DEACTIVATE_DEVICE_RSP     = 0x22
	LORAWAN_MSG_FACTORY_RESET_REQ         = 0x23
	LORAWAN_MSG_FACTORY_RESET_RSP         = 0x24
	LORAWAN_MSG_SET_DEVICE_EUI_REQ        = 0x25
	LORAWAN_MSG_SET_DEVICE_EUI_RSP        = 0x26
	LORAWAN_MSG_GET_DEVICE_EUI_REQ        = 0x27
	LORAWAN_MSG_GET_DEVICE_EUI_RSP        = 0x28
	LORAWAN_MSG_GET_NWK_STATUS_REQ        = 0x29
	LORAWAN_MSG_GET_NWK_STATUS_RSP        = 0x2A
	LORAWAN_MSG_SEND_MAC_CMD_REQ          = 0x2B
	LORAWAN_MSG_SEND_MAC_CMD_RSP          = 0x2C
	LORAWAN_MSG_RECV_MAC_CMD_IND          = 0x2D
	LORAWAN_MSG_SET_CUSTOM_CFG_REQ        = 0x31
	LORAWAN_MSG_SET_CUSTOM_CFG_RSP        = 0x32
	LORAWAN_MSG_GET_CUSTOM_CFG_REQ        = 0x33
	LORAWAN_MSG_GET_CUSTOM_CFG_RSP        = 0x34
	LORAWAN_MSG_GET_SUPPORTED_BANDS_REQ   = 0x35
	LORAWAN_MSG_GET_SUPPORTED_BANDS_RSP   = 0x36
	LORAWAN_MSG_SET_LINKADRREQ_CONFIG_REQ = 0x3B
	LORAWAN_MSG_SET_LINKADRREQ_CONFIG_RSP = 0x3C
	LORAWAN_MSG_GET_LINKADRREQ_CONFIG_REQ = 0x3D
	LORAWAN_MSG_GET_LINKADRREQ_CONFIG_RSP = 0x3E
)

const (
	LORAWAN_STATUS_OK                    = 0x00
	LORAWAN_STATUS_ERROR                 = 0x01
	LORAWAN_STATUS_CMD_NOT_SUPPORTED     = 0x02
	LORAWAN_STATUS_WRONG_PARAMETER       = 0x03
	LORAWAN_STATUS_WRONG_DEVICE_MODE     = 0x04
	LORAWAN_STATUS_DEVICE_NOT_ACTIVATED  = 0x05
	LORAWAN_STATUS_DEVICE_BUSY           = 0x06
	LORAWAN_STATUS_QUEUE_FULL            = 0x07
	LORAWAN_STATUS_LENGTH_ERROR          = 0x08
	LORAWAN_STATUS_NO_FACTORY_SETTINGS   = 0x09
	LORAWAN_STATUS_CHANNEL_BLOCKED       = 0x0A
	LORAWAN_STATUS_CHANNEL_NOT_AVAILABLE = 0x0B
)
