package iu880b

const (
	DEVMGMT_ID = 0x01
	LORAWAN_ID = 0x10
)

const (
	DEVMGMT_MSG_PING_REQ = 0x01 * iota
	DEVMGMT_MSG_PING_RSP
	DEVMGMT_MSG_GET_DEVICE_INFO_REQ
)

const DEVMGMT_MSG_GET_DEVICE_STATUS_REQ = 0x17
const DEVMGMT_MSG_GET_DEVICE_STATUS_RSP = 0x18
